### ISSUE TITLE
index out of range issue on MacOS Catalina

### ISSUE THREAD

**Issue by ashleykleynhans** [ushu/quiver#1]
```panic: runtime error: index out of range [8] with length 8

goroutine 1 [running]:
github.com/ushu/quiver.ReadNotebook(0xc000018240, 0x40, 0x1, 0xc000018240, 0x40, 0x0)
	/Users/ashley/Development/Go/src/github.com/ushu/quiver/quiver.go:407 +0x427
github.com/ushu/quiver.ReadLibrary(0x7ffeefbff21b, 0x11, 0x1, 0x2, 0x0, 0x0)
	/Users/ashley/Development/Go/src/github.com/ushu/quiver/quiver.go:287 +0x22f
main.main()
	/Users/ashley/Development/Go/src/github.com/ushu/quiver/cmd/quiver_to_markdown/main.go:74 +0xdf```

Command used:  quiver_to_markdown Quiver.qvlibrary NOTES/

**Comment by harrtho** [comment]
Hey @ashleykleynhans,

I'm not 100% sure but maybe my [pull-request#2](https://github.com/ushu/quiver/pull/2) will solve your problem too?
